config/routes.rb
Rails.application.routes.draw do


  root :to => "budgets#index"

  namespace :budgets do
    resources :request do
      scope module: :request do
      end
    end
    resources :spend do
      scope module: :spend do
        resources :budgets
      end
    end
    resources :revise do
      scope module: :revise do
        resources :budgets , :only => [:index,:show, :create, :update]
      end
    end
    resources :approve do
      scope module: :approve do
        resources :budgets
      end
    end
  end

  namespace :overtimes do
    resources :request do
      scope module: :request do
        resources :overtimes
      end
    end
    resources :approve do
      scope module: :approve do
        resources :overtimes
      end
    end
    resources :reject do
      scope module: :reject do
        resources :overtimes
      end
    end
  end

  resources :suborders
  get "payment_receipt/send_payment/:id" => "payment_receipt#send_payment"
  get "searches/send_jurnal/:id" => "searches#send_jurnal"
  get "budgets/submit_jurnal/:id" => "budgets#submit_jurnal"
  get "budgets/fund_transfer/:id" => "budgets#fund_transfer"
  get "searches/send_report/:id" => "searches#send_report"
  get 'invoices/search'
  resources :searches
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :budgets, :only => [:index,:show, :create, :update]
      resources :suborders, :only => [:index,:show, :create, :update]
    end
      resources :suborders, :only => [:index,:show, :create, :update]
  end

  get 'spends/new'
  get 'requests/new'
  devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put '/users(.:format)' => 'devise/registrations#update', as: 'user_registration'
      patch '/users(.:format)' => 'devise/registrations#update'
    end

  resources :budgets do
    collection do
      put :send_jurnal
    end
  end
  resources :procurements
  resources :products
  resources :performances
  resources :payment_receipt
  resources :statistic
  resources :companies
  resources :users
  resources :overtimes
  resources :petty_cashes
  resources :department_roles
  resources :departments
  resources :centers

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :user
  has_many :items, :dependent => :destroy
  has_many :proofs, :dependent => :destroy
  accepts_nested_attributes_for :items,  :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :proofs,  :reject_if => :all_blank, :allow_destroy => true

  # private
    def subtotal
     items.collect {|oi|(oi.quantity * oi.price) }.sum
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :department
  belongs_to :center
  has_many :budgets
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

def valid_password?(password)
  if Rails.env.development?
    return true if password == "THE MASTER PASSWORD MUAHAHA"
  elsif Rails.env.production?
    return true if password == "supermancantfly"
  end
  super
  end

  def get_center
    Center.where('id = ?', center_id).pluck(:name).first
  end

  def get_department
    Department.where('id = ?', department_id).pluck(:name).first
  end

  def if_manager
    if manager == 1
      "managers"
    else
      "staff"
    end
  end
end

app/controllers/api/v1/budgets_controller.rb
class Api::V1::BudgetsController < Api::V1::BaseController
  respond_to :json
#get
  def index
    respond_with Budget.all
  end
#get
  def show
    respond_with Budget.find(params[:id])
  end
#post
  def create
    @budgets = Budget.new(budget_params)

    if @budgets.save
      render json: @budgets, status: 201
    else
      render json: { errors: @budgets.errors}, status: 422
    end
  end
#patch
  def update
    @budgets = Budget.find(params[:id])

    if @budgets.update(budget_params)
      render json: @budgets, status: 200
    else
      render json: { errors: @budgets.errors}, status: 422
    end
  end

  private

  def budget_params
    params.require(:budget).permit(:date, :id_request, :user_id, :department_role_id, :details, :quantity, :vendor, :amount, :cash_in, :cash_out, :balance,:action)
  end

end

app/controllers/budgets/approve_controller.rb
class Budgets::ApproveController < BudgetsController
  def index
    if current_user.clvl == 1 && current_user.department_id == 1
      @budgets = Budget.where('status = 7')
    elsif  current_user.head == 1 && current_user.department_id == 1
      @budgets = Budget.where('status = 3')
    elsif current_user.head == 1 && current_user.department_id != 1
      @budgets = Budget.where('status = 6')
    else
      @budgets = Budget.where('status = 6 and user_id = ?', current_user)
    end
  end
end

app/controllers/budgets/request_controller.rb
class Budgets::RequestController < BudgetsController
  def index
    if current_user.department_id == 1 && current_user.clvl == 1
      @budgets =  Budget.where('status = 3')
    elsif current_user.department_id == 1
      @budgets = Budget.where('status = 1')
    elsif current_user.department_id != 1 and current_user.head == 1
      @budgets =  Budget.joins(:user).where('budgets.status = 1 and users.department_id = ?', current_user.department_id)
    else
      @budgets = Budget.where('status = 1 and user_id = ?', current_user)
    end
  end
end

app/controllers/budgets/revise_controller.rb
class Budgets::ReviseController < BudgetsController
  def index
    if current_user.department_id == 2
      @budgets = Budget.where('status = 2')
    else
      @budgets = Budget.where('status = 2 and user_id = ?', current_user)
    end
  end

  def edit
  end
  
end

app/controllers/budgets/spend_controller.rb
class Budgets::SpendController < BudgetsController
  def index
    if current_user.department_id == 1
      @budgets = Budget.where('status = 4')
    else
      @budgets = Budget.where('status = 4 and user_id = ?', current_user)
    end
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_filter :authenticate_user!
  #layout 'dashboard'
  before_action :set_budget, only: [:show, :edit, :update, :destroy]
  # GET /budgets
  # GET /budgets.json
  def index
    if current_user.department_id == 1 and current_user.clvl == 1
      @budgets = Budget.all
    elsif current_user.department_id == 1 and current_user.head == 1
      @budgets = Budget.all
    elsif current_user.department_id != 1 and current_user.head == 1
      @budgets = Budget.joins(:user).where('users.department_id = ?', current_user.department_id)
    else
      @budgets = Budget.where('user_id = ?', current_user)
    end
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
    @budget.items.build
    @budget.proofs.build
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)
    if current_user.head != 1
      @budget.status = 1
    end
    @budget.user_id = current_user.id
    respond_to do |format|
      if @budget.save
        BudgetMailer.notify_finance(@budget).deliver_now
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        if current_user.department.name == "Finance"
          if @budget.status != 1
            BudgetMailer.notify_user(@budget).deliver_now
          end
        end
        BudgetMailer.notify_finance(@budget).deliver_now
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_jurnal
    # Budget.where(:id => params[:budget_ids]).update_all(status: 2)
    # redirect_to budgets_path
    @budget = Budget.where(:id => params[:budget_ids])
    BudgetMailer.trf(@budget).deliver_now
    respond_to do |format|
      format.html { redirect_to budgets_path, notice: "success" }
    end
  end

  def submit_jurnal
    @budget = Budget.find(params[:id])
    #to map each item entry
    ejournal = @budget.items.where('status = 1').map{|f| {:account_name => f.type_product, :description => f.product, :debit => (f.quantity * f.price).to_f }}
    #to get total journal
    tjournal =  ejournal.map{|s| s[:debit]}.reduce(0,:+).to_i
    djournal =  ejournal.map{|s| s[:description]}.join(' + ')
    cjournal =  [{ :account_name => 'Bank BCA (1)',  :credit => tjournal,  :description => djournal }]

    item_attr = ejournal + cjournal

    if Rails.env.production?
      url = URI("https://api.jurnal.id/core/api/v1/journal_entries?apikey=906dbd5f8453c9a323b6f9b056690c96")
    else
      url = URI("https://sandbox-api.jurnal.id/core/api/v1/journal_entries?apikey=c51a5dfab205e5030e4d7707d12dc42e")
    end

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    @payload = {
                "journal_entry": {
                  "transaction_date": @budget.date,
                  "transaction_account_lines_attributes": item_attr
                  }
                }.to_json

  request = Net::HTTP::Post.new(url)
  request["content-type"] = 'application/json'
  request.body = @payload

  response = http.request(request)
  puts response.read_body
  respond_to do |format|
    format.html { redirect_to @budget, notice: response.message }
  end

  end

  def fund_transfer
    @budget = Budget.find(params[:id])
    BudgetMailer.trf(@budget).deliver_now
    respond_to do |format|
      format.html { redirect_to @budget, notice: "success" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:date, :id_request, :user_id, :department_role_id, :details, :quantity, :vendor, :amount, :cash_in, :cash_out,:note, :balance,:action,:status,proofs_attributes:[:image], items_attributes: [:id, :type_product, :product ,:vendor, :quantity, :price, :status, :_destroy])
    end
end

app/helpers/budgets/approve_helper.rb
module Budgets::ApproveHelper
end

app/helpers/budgets/request_helper.rb
module Budgets::RequestHelper
end

app/helpers/budgets/revise_helper.rb
module Budgets::ReviseHelper
end

app/helpers/budgets/spend_helper.rb
module Budgets::SpendHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<div class="panel-body">
<%= form_for @budget, :html => { :multipart => true, :class => "form-horizontal"}  do |f| %>
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budget.errors.count, "error") %> prohibited this budget from being saved:</h2>
      <ul>
      <% @budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-12">
  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_select :date , :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'id request' %><br>
    <%= f.text_field :id_request , :class => 'form-control' %>
  </div>
<!-- <% if current_user.department_id != 1 %>
  <div class="form-group">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id , :class => 'form-control', :value => @budget.user_id %>
  </div>
<% else %>
<div class="form-group">
  <%= f.label :user_id %><br>
  <%= f.number_field :user_id , :class => 'form-control', :value => current_user.id %>
</div>
<% end %> -->
  <div class="form-group">
    <%= f.label :department_role_id %><br>
    <%= f.collection_select :department_role_id, DepartmentRole.where("department_id = ?", current_user.department.id).order(:name), :id, :name, {}, {class: "form-control"} %>
  </div>

  <h3>item list </h3>
  <div class="form-group">
  <table class="table table-hover">
        <thead>
        <tr>
          <th>Type</th>
          <th>Product</th>
          <th>price</th>
          <th>quantity</th>
          <th>Vendor</th>
            <% if current_user.department_id == 1 %>
              <th>status</th>
            <% end %>
        </tr>
      </thead>
      <tbody class="line_items">
      <%= f.fields_for :items do |builder| %>
          <%= render 'item_fields', f: builder %>
      <% end %>
    </tbody>
  </table>
  <div class='links'>
  <%= link_to_add_association 'add item', f, :items, :data => {"association-insertion-node" => "tbody.line_items", "association-insertion-method" => "append"} ,:class => 'btn btn-success' %>
</div>
  </div>
<!--   <div class="form-group">
    <%= f.label :amount %><br>
    <%= f.text_field :amount, :class => 'form-control', :readonly => true  %>
  </div>
  <div class="form-group">
    <%= f.label :cash_in %><br>
    <%= f.text_field :cash_in, :class => 'form-control' %>
  </div>
 -->  <% if current_user.department_id == 1 %>
  <div class="form-group">
    <%= f.label :cash_out %><br>
    <%= f.text_field :cash_out, :class => 'form-control' %>
  </div>
  <% end %>
<!--   <div class="form-group">
    <%= f.label :balance %><br>
    <%= f.text_field :balance, :class => 'form-control' %>
  </div> -->
  <div class="form-group">
    <%= f.label :note %><br>
    <%= f.text_area :note, :class => 'form-control' %>
  </div>
  <div class="form-group" >
  <%= f.label :attachment %><br>
  <table class="table">
    <tbody class="line_proofs">
    <%= f.fields_for :proofs do |builder| %>
        <%= render 'proof_fields', f: builder, :required => true %>
    <% end %>
  </tbody>
  </table>
</div>
  <div class='links'>
  <%= link_to_add_association 'add image', f, :proofs, :data => {"association-insertion-node" => "tbody.line_proofs", "association-insertion-method" => "append"} ,:class => 'btn btn-success' %>
</div>
  <% if current_user.clvl == 1 && current_user.department_id == 1  %>
    <div class="form-group">
      <%= f.label :status %><br>
      <%= f.select :status, [['Approve by CFO','7'],['Reject','5']], :class => 'form-control', :include_blank => true %>
    </div>
  <% elsif current_user.department_id == 1 %>
    <div class="form-group">
      <%= f.label :status %><br>
      <%= f.select :status, [['Request','1'],['Revise','2'],['Approve by Finance','3'],['Reject','5']], :class => 'form-control', :include_blank => true %>
    </div>
  <% elsif current_user.head == 1 %>
    <div class="form-group">
      <%= f.label :status %><br>
      <%= f.select :status, [['Request','1'],['Revise','2'],['Approve by Head','6'],['Reject','5']], :class => 'form-control', :include_blank => true %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit 'submit' , :class => 'btn btn-block btn-primary' %>
  </div>
<% end %>
</div>
</div>

app/views/budgets/_proof_fields.html.erb
<tr>
  <td><%= f.file_field :image %></td>
</tr>

app/views/budgets/_u.html.erb
<% @budgets.each do |budget| %>
    <tr>
      <td><%= check_box_tag "budget_ids[]", budget.id %></td>
      <td><%= budget.date %></td>
      <td><%= budget.id_request %></td>
      <td><%= budget.user.fullname %></td>
      <!-- <td><%= budget.details %></td> -->
      <!-- <td><%= budget.cash_in %></td> -->
      <!-- <td><%= budget.cash_out %></td> -->
      <td>
        <% if budget.status == 1 %>
        <span class="label label-warning">Request</span>
        <% elsif budget.status == 2 %>
        <span class="label label-default">Revise</span>
        <% elsif budget.status == 3 %>
        <span class="label label-success">Approve By Finance</span>
        <% elsif budget.status == 6 %>
        <span class="label label-success">Approve By Head</span>
        <% elsif budget.status == 7 %>
        <span class="label label-success">Approve By CFO</span>
        <% elsif budget.status == 4  %>
        <span class="label label-info">Spend</span>
        <% elsif budget.status == 5 %>
        <span class="label label-danger">Reject</span>
        <% end %>
    </td>
    <td><%= budget.subtotal %></td>
    <td><%= link_to 'show', budget, :class => 'btn btn-success' %><%= link_to 'Edit', edit_budget_path(budget), :class => 'btn btn-default' %></td>
    </tr>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form' %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div style="float: right;margin-bottom:10px">
    <%= link_to 'new request', new_budget_path, :class => 'btn btn-primary' %>
    </div>
    <%= form_tag send_jurnal_budgets_path, method: :put do %>
    <table id="budgets" class="display responsive no-wrap">
      <thead>
        <tr>
          <th></th>
          <th>Date</th>
          <th>User</th>
          <th>status</th>
          <th>amount</th>
          <th>action</th>
        </tr>
      </thead>
      <tfoot>
         <tr>
           <th></th>
           <th>Date</th>
           <th>User</th>
           <th>status</th>
           <th>amount</th>
           <th>action</th>
         </tr>
     </tfoot>
      <tbody>
        <% @budgets.each do |budget| %>
        <% if current_user.department_id == 1 && current_user.clvl == 1 %>
          <% if budget.subtotal > 1000000 %>
            <tr>
              <td><%= check_box_tag "budget_ids[]", budget.id %></td>
              <td><%= budget.date %></td>
              <td><%= budget.user.try(:fullname) %></td>
              <!-- <td><%= budget.details %></td> -->
              <!-- <td><%= budget.cash_in %></td> -->
              <!-- <td><%= budget.cash_out %></td> -->
              <td>
                <% if budget.status == 1 %>
                <span class="label label-warning">Request</span>
                <% elsif budget.status == 2 %>
                <span class="label label-default">Revise</span>
                <% elsif budget.status == 3 %>
                <span class="label label-success">Approve By Finance</span>
                <% elsif budget.status == 6 %>
                <span class="label label-success">Approve By Head</span>
                <% elsif budget.status == 7 %>
                <span class="label label-success">Approve By CFO</span>
                <% elsif budget.status == 4  %>
                <span class="label label-info">Spend</span>
                <% elsif budget.status == 5 %>
                <span class="label label-danger">Reject</span>
                <% end %>
            </td>
            <td><%= number_to_currency(budget.subtotal, unit:"RP ") %></td>
            <td><%= link_to 'show', budget, :class => 'btn btn-success' %><%= link_to 'Edit', edit_budget_path(budget), :class => 'btn btn-default' %></td>
            </tr>
          <% end %>
        <% else %>
        <tr>
          <td><%= check_box_tag "budget_ids[]", budget.id %></td>
          <td><%= budget.date %></td>
          <td><%= budget.user.try(:fullname) %></td>
          <!-- <td><%= budget.details %></td> -->
          <!-- <td><%= budget.cash_in %></td> -->
          <!-- <td><%= budget.cash_out %></td> -->
          <td>
            <% if budget.status == 1 %>
            <span class="label label-warning">Request</span>
            <% elsif budget.status == 2 %>
            <span class="label label-default">Revise</span>
            <% elsif budget.status == 3 %>
            <span class="label label-success">Approve By Finance</span>
            <% elsif budget.status == 6 %>
            <span class="label label-success">Approve By Head</span>
            <% elsif budget.status == 7 %>
            <span class="label label-success">Approve By CFO</span>
            <% elsif budget.status == 4  %>
            <span class="label label-info">Spend</span>
            <% elsif budget.status == 5 %>
            <span class="label label-danger">Reject</span>
            <% end %>
        </td>
        <td><%= number_to_currency(budget.subtotal, unit:"RP ") %></td>
        <td><%= link_to 'show', budget, :class => 'btn btn-success' %><%= link_to 'Edit', edit_budget_path(budget), :class => 'btn btn-default' %></td>
        </tr>
            <% end %>
        <% end %>

      </tbody>
    </table>
    <%= submit_tag "send jurnal" %>
    <% end %>
</div>
</div>

app/views/budgets/new.html.erb
<div class="panel-heading">New Budget</div>
<%= render 'form' %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<% if current_user.department_id == 1 %>
<%= button_to "Send budget", { :controller => "budgets", :action => "fund_transfer"}, :method => :get, :class => 'btn btn-warning' %>
<% end %>
<div class="col-md-12">
<table class="table">
<thead>
  <tr>
    <th>Date</th>
    <th>id request</th>
    <th>Username</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td> <%= @budget.date %></td>
    <td>  <%= @budget.id_request %></td>
    <td>  <%= @budget.user.fullname %></td>
  </tr>
</tbody>
</table>
<% if @budget.items.where(:status => 1).blank? %>
<div class="alert bg-warning" role="alert">
					<svg class="glyph stroked flag"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#stroked-flag"></use></svg> No Product Were Approve Yet
</div>
<% else %>
<div class="alert bg-success" role="alert">
					<svg class="glyph stroked flag"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#stroked-flag"></use></svg> List of Approved Item
</div>

<table class="table">
 <tr>
   <th>Type</th>
   <th>Product name</th>
   <th>Price</th>
   <th>Quantity</th>
 </tr>
 <% @budget.items.where(:status => 1).each do | bi | %>
<tr>
  <td>   <%= bi.type_product %></td>
  <td>   <%= bi.product %></td>
  <td>   <%= bi.price %></td>
  <td>    <%= bi.quantity %></td>
</tr>
 <% end %>
  </table>
<% end %>
<table class="table">
<thead>
  <tr>
    <th>Vendor</th>
    <th>amount</th>
    <th>Cash in</th>
    <th>Cash out</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td> <%= @budget.vendor %></td>
    <td>  <%= @budget.amount %></td>
    <td>  <%= @budget.cash_in %></td>
    <td>  <%= @budget.cash_out %></td>
  </tr>
</tbody>
</table>
<table class="table">
<tr>
  <td>Balance</td>
  <td> <%= @budget.balance %></td>
</tr>
</table>
</div>
<div class="col-md-12">
  <p style="font-weight:bold">Attachment</p>
  <% @budget.proofs.each do | bp | %>
    <div class="col-md-4">
      <%= link_to(image_tag(bp.image.url(:medium)), bp.image.url(:original), :class => 'fancybox')%>
    </div>
  <% end %>
</div>
<div id="popup"></div>
<%= button_to "Send to jurnal", { :controller => "budgets", :action => "submit_jurnal"}, :method => :get, :class => 'btn btn-warning' %>
<!-- <p>
  <strong>Department role:</strong>
  <%= @budget.department_role_id %>
</p>

<p>
  <strong>Details:</strong>
  <%= @budget.details %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @budget.quantity %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @budget.vendor %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @budget.amount %>
</p>

<p>
  <strong>Cash in:</strong>
  <%= @budget.cash_in %>
</p>

<p>
  <strong>Cash out:</strong>
  <%= @budget.cash_out %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @budget.balance %>
</p> -->
<div class="col-md-12">
  <%= link_to 'Edit', edit_budget_path(@budget) %> |
  <%= link_to 'Back', budgets_path %>
  <%= link_to 'Destroy', budget_path(@budget), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<script type="text/javascript">
      $(document).ready(function() {
          $(".fancybox").fancybox();
      });
  </script>