config/routes.rb
Rails.application.routes.draw do


  root :to => "budgets#index"

  namespace :budgets do
    resources :request do
      scope module: :request do
      end
    end
    resources :spend do
      scope module: :spend do
        resources :budgets
      end
    end
    resources :revise do
      scope module: :revise do
        resources :budgets , :only => [:index,:show, :create, :update]
      end
    end
    resources :approve do
      scope module: :approve do
        resources :budgets
      end
    end
  end

  namespace :overtimes do
    resources :request do
      scope module: :request do
        resources :overtimes
      end
    end
    resources :approve do
      scope module: :approve do
        resources :overtimes
      end
    end
    resources :reject do
      scope module: :reject do
        resources :overtimes
      end
    end
  end

  resources :suborders
  get "payment_receipt/send_payment/:id" => "payment_receipt#send_payment"
  get "searches/send_jurnal/:id" => "searches#send_jurnal"
  get "budgets/submit_jurnal/:id" => "budgets#submit_jurnal"
  get "budgets/fund_transfer/:id" => "budgets#fund_transfer"
  get "searches/send_report/:id" => "searches#send_report"
  get 'invoices/search'
  resources :searches
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :budgets, :only => [:index,:show, :create, :update]
      resources :suborders, :only => [:index,:show, :create, :update]
    end
      resources :suborders, :only => [:index,:show, :create, :update]
  end

  get 'spends/new'
  get 'requests/new'
  devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put '/users(.:format)' => 'devise/registrations#update', as: 'user_registration'
      patch '/users(.:format)' => 'devise/registrations#update'
    end

  resources :budgets do
    collection do
      put :send_jurnal
    end
  end
  resources :procurements
  resources :products
  resources :performances
  resources :payment_receipt
  resources :statistic
  resources :companies
  resources :users
  resources :overtimes
  resources :petty_cashes
  resources :department_roles
  resources :departments
  resources :centers

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_one :user
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        create_company
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_company
    require 'uri'
    require 'net/http'

    if Rails.env.production?
      url = URI("https://api.jurnal.id/core/api/v1/customers?apikey=906dbd5f8453c9a323b6f9b056690c96")
    else
      url = URI("https://sandbox-api.jurnal.id/core/api/v1/customers?apikey=c51a5dfab205e5030e4d7707d12dc42e")
    end

    http = Net::HTTP.new(url.host, url.port)
    if Rails.env.production?
    http.use_ssl = true
    else
    http.use_ssl = true
    end
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    ap = "Accounts Payable"
    ar = Center.where('tag = ?', @company.center).pluck("receivable").first

    @payload = {
        "customer": {
        "display_name": @company.name,
        "email": @company.email,
        "default_ar_account_name": ar,
        "default_ap_account_name": ap
                          } }.to_json

    request = Net::HTTP::Post.new(url)
    request["content-type"] = 'application/json'
    request.body = @payload

    response = http.request(request)
    puts response.read_body
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :email,:center)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email , :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :center, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4 col-xs-12">
        <%= f.collection_select :center, Center.order(:name) ,:tag,:name,{ :prompt => true}, {:class => 'form-control'} %>
    </div>
    <%=f.error_span(:center) %>
  </div>
  <div class="actions">
    <%= f.submit 'submit', :class => 'btn btn-block btn-default'%>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing Companies</h1>
<% if Rails.env.production? %>
<p> production </p>
<% else %>
<p>dev</p>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.email %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>