config/routes.rb
Rails.application.routes.draw do


  root :to => "budgets#index"

  namespace :budgets do
    resources :request do
      scope module: :request do
      end
    end
    resources :spend do
      scope module: :spend do
        resources :budgets
      end
    end
    resources :revise do
      scope module: :revise do
        resources :budgets , :only => [:index,:show, :create, :update]
      end
    end
    resources :approve do
      scope module: :approve do
        resources :budgets
      end
    end
  end

  namespace :overtimes do
    resources :request do
      scope module: :request do
        resources :overtimes
      end
    end
    resources :approve do
      scope module: :approve do
        resources :overtimes
      end
    end
    resources :reject do
      scope module: :reject do
        resources :overtimes
      end
    end
  end

  resources :suborders
  get "payment_receipt/send_payment/:id" => "payment_receipt#send_payment"
  get "searches/send_jurnal/:id" => "searches#send_jurnal"
  get "budgets/submit_jurnal/:id" => "budgets#submit_jurnal"
  get "budgets/fund_transfer/:id" => "budgets#fund_transfer"
  get "searches/send_report/:id" => "searches#send_report"
  get 'invoices/search'
  resources :searches
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :budgets, :only => [:index,:show, :create, :update]
      resources :suborders, :only => [:index,:show, :create, :update]
    end
      resources :suborders, :only => [:index,:show, :create, :update]
  end

  get 'spends/new'
  get 'requests/new'
  devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put '/users(.:format)' => 'devise/registrations#update', as: 'user_registration'
      patch '/users(.:format)' => 'devise/registrations#update'
    end

  resources :budgets do
    collection do
      put :send_jurnal
    end
  end
  resources :procurements
  resources :products
  resources :performances
  resources :payment_receipt
  resources :statistic
  resources :companies
  resources :users
  resources :overtimes
  resources :petty_cashes
  resources :department_roles
  resources :departments
  resources :centers

end

app/models/overtime.rb
class Overtime < ActiveRecord::Base
  belongs_to :user
  belongs_to :center
end

app/controllers/overtimes/approve_controller.rb
class Overtimes::ApproveController < OvertimesController
  def index
    if current_user.department_id == 5
      @overtimes = Overtime.where('status = ?', "2")
    else
      @overtimes = Overtime.where('status = ? and user_id = ?',"2", current_user)
    end
  end
end

app/controllers/overtimes/reject_controller.rb
class Overtimes::RejectController < OvertimesController
  def index
    if current_user.department_id == 5
      @overtimes = Overtime.where('status = ?',"3")
    else
      @overtimes = Overtime.where('status = ? and user_id = ?',"3", current_user)
    end
  end
end

app/controllers/overtimes/request_controller.rb
class Overtimes::RequestController < OvertimesController
  def index
    if current_user.department_id == 5
      @overtimes = Overtime.where('status = ?',"1")
    else
      @overtimes = Overtime.where('status = ? and user_id = ?',"1", current_user)
    end
  end
end

app/controllers/overtimes_controller.rb
class OvertimesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_overtime, only: [:show, :edit, :update, :destroy]

  # GET /overtimes
  # GET /overtimes.json
  def index
    if current_user.department_id == 1 || current_user.department_id == 5 
      @overtimes = Overtime.all
    else
      @overtimes = Overtime.where('user_id = ?', current_user)
    end
  end

  # GET /overtimes/1
  # GET /overtimes/1.json
  def show
  end

  # GET /overtimes/new
  def new
    @overtime = Overtime.new
  end

  # GET /overtimes/1/edit
  def edit
  end

  # POST /overtimes
  # POST /overtimes.json
  def create
    @overtime = Overtime.new(overtime_params)
    @overtime.user_id = current_user.id
    @overtime.center_id = current_user.center_id
    @overtime.status = "1"
    @overtime.amount = ((Time.parse(params[:overtime][:end]) - Time.parse(params[:overtime][:date]))/3600 )* current_user.ot_fee
    respond_to do |format|
      if @overtime.save
        BudgetMailer.new_ot(@overtime).deliver_now
        # @overtime.amount = @overtime.end - @overtime.date
        format.html { redirect_to @overtime, notice: 'Overtime was successfully created.' }
        format.json { render :show, status: :created, location: @overtime }
      else
        format.html { render :new }
        format.json { render json: @overtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /overtimes/1
  # PATCH/PUT /overtimes/1.json
  def update
    respond_to do |format|
      if @overtime.update(overtime_params)
        if @overtime.status == "2"
          BudgetMailer.ot_approve(@overtime).deliver_now
        elsif @overtime.status == "3"
          BudgetMailer.rt_approve(@overtime).deliver_now
        end
        format.html { redirect_to @overtime, notice: 'Overtime was successfully updated.' }
        format.json { render :show, status: :ok, location: @overtime }
      else
        format.html { render :edit }
        format.json { render json: @overtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /overtimes/1
  # DELETE /overtimes/1.json
  def destroy
    @overtime.destroy
    respond_to do |format|
      format.html { redirect_to overtimes_url, notice: 'Overtime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_overtime
      @overtime = Overtime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def overtime_params
      params.require(:overtime).permit(:id, :date, :user_id, :note, :status, :center_id, :end)
    end
end

app/helpers/overtimes/approve_helper.rb
module Overtimes::ApproveHelper
end

app/helpers/overtimes/reject_helper.rb
module Overtimes::RejectHelper
end

app/helpers/overtimes/request_helper.rb
module Overtimes::RequestHelper
end

app/helpers/overtimes_helper.rb
module OvertimesHelper
end

app/views/overtimes/_form.html.erb
<%= form_for(@overtime) do |f| %>
  <% if @overtime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@overtime.errors.count, "error") %> prohibited this overtime from being saved:</h2>

      <ul>
      <% @overtime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.text_field :date, :id => 'min', :class => 'form-control datetimepicker' %>
  </div>

  <div class="form-group">
    <%= f.label :end %><br>
    <%= f.text_field :end, :id => 'max', :class => 'form-control datetimepicker' %>
  </div>
  <!-- <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div> -->
  <div class="form-group">
    <%= f.label :note %><br>
    <%= f.text_field :note, :class => 'form-control' %>
  </div>
  <% if current_user.department_id == 5 %>
  <div class="form-group">
    <%= f.label :status %><br>
    <td><%= f.select :status, [['Request','1'],['Approve','2'],['Reject','3']], :class => 'form-control', :include_blank => true %></td>

    <!-- <%= f.select(:status, options_for_select(['Request','Approve','Reject'], :selected => f.object.status), {:class => 'form-control'}) %> -->
    <!-- <%= f.text_field :status, :editatble => false %> -->
  </div>
  <% end %>

  <!-- <div class="field">
    <%= f.label :center_id %><br>
    <%= f.collection_select :center_id, Center.all.order(:name), :id, :name, {}, {class: "form-control"} %>
    <%= f.number_field :center_id %>
  </div> -->
    <%= f.submit 'Submit', :class => 'btn btn-block btn-success'  %>
<% end %>
<script type="text/javascript">
$(document).ready(function() {
  $('#min').datetimepicker({
    format: 'YYYY-MM-DD HH:mm'
    });
    $('#max').datetimepicker({
      format: 'YYYY-MM-DD HH:mm'
      });
  });
</script>

app/views/overtimes/edit.html.erb
<h1>Editing Overtime</h1>

<%= render 'form' %>

<%= link_to 'Show', @overtime %> |
<%= link_to 'Back', overtimes_path %>

app/views/overtimes/index.html.erb
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.1/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.1/js/buttons.flash.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.1/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.1/js/buttons.print.min.js"></script>
<style media="screen">
  .dt-button{
    padding: 0.5%;
    margin-left: 0.5%;
    border: 1px solid #30a5ff;
  }
</style>
<div class="row">
    <div class="col-md-12">
<%= link_to 'New Overtime', new_overtime_path, :class => 'btn btn-success' %>
<p id="notice"><%= notice %></p>
<h3>Overtimes</h3>
<table class="table">
  <tbody><tr>
      <td>Minimum:</td>
      <td><input type="text" id="min" name="min"></td>
  </tr>
  <tr>
      <td>Maximum:</td>
      <td><input type="text" id="max" name="max"></td>
  </tr>
</tbody></table>
<table class="table" id="overtime">
  <thead>
    <tr>
      <th>Date</th>
      <th>User</th>
      <th>Note</th>
      <th>Status</th>
      <th>Center</th>
      <th>amount</th>
      <th>duration</th>
      <th>action</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @overtimes.each do |overtime| %>
      <tr>
        <td><%= overtime.date.try(:strftime,'%Y-%m-%d') %></td>
        <td><%= overtime.user.fullname %></td>
        <td><%= overtime.try(:note) %></td>
        <td>
          <% if overtime.status == "1" %>
          <span class="label label-warning">Request</span>
          <% elsif overtime.status == "2" %>
          <span class="label label-success">Approve</span>
          <% elsif overtime.status == "3" %>
          <span class="label label-danger">Reject</span>
          <% end %>
        </td>
        <td><%= overtime.center.name %></td>
        <td><%= (overtime.end  - overtime.date)/3600 * overtime.user.ot_fee %></td>
        <td><%= (overtime.end  - overtime.date)/3600 %></td>
        <!-- <td><%= link_to 'Show', overtime %></td> -->
        <td><%= link_to 'Edit', edit_overtime_path(overtime) %></td>
        <!-- <td><%= link_to 'Destroy', overtime, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<script type="text/javascript">
$.fn.dataTableExt.afnFiltering.push(
    function( oSettings, aData, iDataIndex ) {
        var iFini = document.getElementById('min').value;
        var iFfin = document.getElementById('max').value;
        var iStartDateCol = 0;
        var iEndDateCol = 0;

        iFini=iFini.substring(0,4) + iFini.substring(5,7)+ iFini.substring(8,10);
        iFfin=iFfin.substring(0,4) + iFfin.substring(5,7)+ iFfin.substring(8,10);

        var datofini=aData[iStartDateCol].substring(0,4) + aData[iStartDateCol].substring(5,7)+ aData[iStartDateCol].substring(8,10);
        var datoffin=aData[iEndDateCol].substring(0,4) + aData[iEndDateCol].substring(5,7)+ aData[iEndDateCol].substring(8,10);

        if ( iFini === "" && iFfin === "" )
        {
            return true;
        }
        else if ( iFini <= datofini && iFfin === "")
        {
            return true;
        }
        else if ( iFfin >= datoffin && iFini === "")
        {
            return true;
        }
        else if (iFini <= datofini && iFfin >= datoffin)
        {
            return true;
        }
        return false;
    }
);
$(document).ready(function() {
  $('#min').datetimepicker({
    format: 'YYYY-MM-DD'
    });
  $('#max').datetimepicker({
    format: 'YYYY-MM-DD'
    });

  var table = $('#overtime').DataTable({
    order: [[ 0, "desc" ]],
    dom: 'Bfrtip',
     buttons: [
          'csv', 'pdf'
     ]
    });
    // Add event listeners to the two range filtering inputs
  $('#min').keyup( function() { table.draw(); } );
  $('#max').keyup( function() { table.draw(); } );
  } );
</script>

app/views/overtimes/new.html.erb
<h1>New Overtime</h1>

<%= render 'form' %>

<%= link_to 'Back', overtimes_path %>

app/views/overtimes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @overtime.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @overtime.user_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @overtime.note %>
</p>

<p>
  <strong>Status:</strong>
  <%= @overtime.status %>
</p>

<p>
  <strong>Center:</strong>
  <%= @overtime.center_id %>
</p>

<%= link_to 'Edit', edit_overtime_path(@overtime) %> |
<%= link_to 'Back', overtimes_path %>